// This file is auto-generated by @hey-api/openapi-ts

export { getHello, type Options } from './sdk.gen';
export type { ClientOptions, GetHelloData, GetHelloResponse, GetHelloResponses, HelloResponse } from './types.gen';
